blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='post_list')
]

diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'

urlpatterns = [
    path('', views.top, name='top')
]

myprofile/urls.py
from django.urls import path
from . import views

app_name = 'myprofile'

urlpatterns = [
    path('', views.top, name='top'),
    path('works/', views.works, name='works'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('form/', views.Form.as_view(), name='form'),
    path('thanks/', views.Thanks.as_view(), name='thanks'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/', include('diaries.urls')),
    path('reviews/', include('reviews.urls')),
    path('blog/', include('blog.urls')),
    path('', include('myprofile.urls')),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.ReviewList.as_view(), name='review_list'),
    path('detail/<int:pk>/', views.ReviewDetail.as_view(), name='review_detail'),
    path('create/', views.ReviewCreate.as_view(), name='review_create'),
    path('update/<int:pk>/', views.ReviewUpdate.as_view(), name='review_update'),
    path('delete/<int:pk>/', views.ReviewDelete.as_view(), name='review_delete'),
]

blog/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.conf import settings



class Tag(models.Model):
    name = models.CharField('タグ名', max_length=255, unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255, unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    

    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ', blank=True)
    tags = models.ManyToManyField(Tag, verbose_name='タグ', blank=True)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, verbose_name='投稿者')
    created_at = models.DateTimeField('作成日', auto_now_add=True)
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    text = models.TextField('本文')
    target = models.ForeignKey(Post, on_delete=models.PROTECT, verbose_name='どの記事へのコメントか')

    def __str__(self):
        return self.text[:20]

diaries/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class CreatedAt(models.Model):
    name = models.CharField('作成日', max_length=255)


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=255)
    created_at = models.ForeignKey(CreatedAt, verbose_name='作成日', null=True, blank=True, on_delete=models.PROTECT)
  

    def __str__(self):
        return self.name


class Diary(models.Model):
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)
    def __str__(self):
        return 'カテゴリ:{} 本文:{}'.format(self.category, self.text[:10])

myprofile/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Diery(models.Model):
    category = models.CharField('カテゴリ', max_length=255)
    text = models.TextField('本文')
    created_at = models.DateTimeField('作成日', default=timezone.now)

reviews/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Review(models.Model):
    STARS = (
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★')
    )

    store_name = models.CharField('店名', max_length=255)
    title = models.CharField('タイトル', max_length=255)
    text = models.TextField('口コミテキスト', blank=True)
    stars = models.IntegerField('星の数', choices=STARS)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

myprofile/forms.py
from django import forms

class ContactForm(forms.Form):
    CATEGORIES = (
        ('1', 'お仕事の依頼'),
        ('2', 'サイト内容に関するお問い合わせ'),
    )

    name = forms.CharField(
        label='お名前', max_length=50,
        required=False, help_text='※任意'
    )
    email = forms.EmailField(
        label='メールアドレス', required=False, help_text='※任意'
    )
    text = forms.CharField(label='お問い合わせ内容', widget=forms.Textarea)
    category = forms.ChoiceField(label='カテゴリ', choices=CATEGORIES)

reviews/forms.py
from django import forms
from .models import Review

class ReviewCreateForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = ('created_at',)

blog/views.py
from django.shortcuts import render

# Create your views here.

from django.views import generic
from .models import Post


class PostList(generic.ListView):
    model = Post
    ordering = '-created_at'

diaries/views.py
from django.shortcuts import render
from .models import Diary
# Create your views here.

def top(request):
    context = {
        'diary_list': Diary.objects.all(),
    }
    return render(request, 'diaries/diary_list.html', context)

myprofile/views.py
from django.shortcuts import render


# Create your views here

from django.http import HttpResponse
from django.template import loader
from django.urls import reverse_lazy
from django.views import generic
from .forms import ContactForm
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

def top(request):
    context = {
        'name': 'ちびはる',
    }
    return render(request, 'myprofile/top.html', context)

def works(request):
    return render(request, 'myprofile/works.html')


def portfolio(request):
    return render(request, 'myprofile/portfolio.html')


class Form(generic.FormView):
    form_class = ContactForm
    success_url = reverse_lazy('myprofile:thanks')
    template_name = 'myprofile/form.html'

    def form_valid(self, form):
        subject = 'お問い合わせがあったよ'
        message = render_to_string('myprofile/mail.txt', form.cleaned_data, self.request)
        from_email = 'chibiharujijimasa@gmail.com'
        recipient_list = []
        bcc = ['chibiharujijimasa@gmail.com']
        email = EmailMessage(subject, message, from_email, recipient_list, bcc)
        email.send()
        return redirect('myprofile:thanks')

class Thanks(generic.TemplateView):
    template_name = 'myprofile/thanks.html'

reviews/views.py
from django.shortcuts import render
from .models import Review
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ReviewCreateForm
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.


class ReviewList(generic.ListView):
    model = Review

    
class ReviewDetail(generic.DetailView):
    model = Review

class ReviewCreate(generic.CreateView):
    model = Review
    form_class = ReviewCreateForm
    success_url = reverse_lazy('reviews:review_list')

class ReviewUpdate(generic.UpdateView):
    model = Review
    form_class = ReviewCreateForm
    success_url = reverse_lazy('reviews:review_list')

class ReviewDelete(generic.DeleteView):
    model = Review
    success_url = reverse_lazy('reviews:review_list')

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Harumasa's-blog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
<header class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class='title'><a href="{% url 'blog:post_list' %}" class="has-text-white">Harumasa's blog</a></h1>
            <h2 class="subtitle">未経験エンジニアブログ</h2>
        </div>
    </div>
</header>

<div class="sectoin">
    <div class="container">
        <div class="columns">
            <main class="column is-7">
                {% block content %}{% endblock %}
            </main>
            <aside class="column is-offset-1 is-4">
                <p>サイドバー</p>
            </aside>
        </div>
    </div>
</div>

</body>
</html>
            

blog/templates/blog/post_list.html
{% extends 'myprofile/base.html' %}

{% block content %}
<h1 class="h1_title">My Blog</h1>
    {% for post in post_list %}
    
        <article class="blog_box">
            <h1><a href="">{{ post.title }}</a></h1>
            <p>投稿者: {{ post.writer }}</p>
            <p>作成日: {{ post.created_at }}</p>
            <p>更新日: {{ post.updated_at }}</p>
            <p>カテゴリ: {{ post.category }}<p>
            <p>タグ: {% for tag in post.tags.all %}{{ tag }},{% endfor %}</p>
        </article>
    {% endfor %}
{% endblock %}

diaries/templates/diaries/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ちびはる日記</title>
    <style>
        * {
            margin: 0;
        }

        body {
            color:#333;
            max-width: 500px;
            margin: 0 auto;
            padding-left: 40px;
            padding-right: 40px;
        }

        body > header {
            color: #999;
            font-size: 40px;
            margin-top: 100px;
            margin-bottom: 50px;
            text-align: center;
        }

        main {
            border-top: solid 1px #ddd;
            padding-top: 40px;
        }

        main > article {
            border-bottom: solid 1px #ddd;
            margin-bottom: 40px;
            padding-bottom: 40px;
        }

        main > article > span.category {
            color: #999;
        }

        main > article > time {
            color: #999;
        }
    </style>
</head>
<body>
<header>ちびはる日記</header>
<main>
    {% block content %}{% endblock %}
</main>
</body>
</html>

diaries/templates/diaries/diary_list.html
{% extends 'diaries/base.html' %}

{% block content %}
    {% for diary in diary_list %}
        <article>
            <time>{{ diary.created_at | date:'Y/n/j G:i'}}</time> - <span class="category">{{ diary.category }}</span><br>
            <p>{{ diary.text | linebreaks }}</p>
        </article>
    {% endfor %}
{% endblock %}

myprofile/templates/myprofile/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <style>
        header h1{
            text-align: center;
        }
        nav ul{
            margin: 0;
            padding: 0;
        }
        nav ul li {
            width: 800px;
            display: flex;
            justify-content: center;
            justify-content: space-between;
            margin-right: auto;
            margin-left: auto;
            max-width:100%;
        }
        nav ul li a{
            color: black;
            text-decoration: none;
        }
        .h1_title {
            margin-left: 300px;
        }
        .top_article {
            width:900px;
            max-width: 100%;
            margin-right: auto;
            margin-left: auto;
            display: flex;
            justify-content: space-between;
        }
        .box_1 {
            width: 300px;
        }
        
        .box_2 {
            width: 300px;
        }
        .skill_ul {
            list-style: none;
            display: block;
            margin: 0;
            padding: 0;
        }
        .box_3 {
            width: 300px;
        }
        h2{
            text-align: center;
        }
        .works_table {
            margin-right: auto;
            margin-left: auto;
        }
        .works_th {
            text-align: left;
        }
        .works_td {
            text-align: center;
        }
        .works_table {
            width: 700px;
        }
        .main_form {
            width: 600px;
            height: 600px;
            margin-right: auto;
            margin-left: auto;
        }
        .thanks_p {
            margin-left: 300px;
        }
        .errorlist {
            margin: 0;
            padding: 0;
            list-style-type: none;
            color: red;
        }
        div.field {
            margin-bottom: 20px;
        }
        div.field > span.helptext {
            font-size: 14px;
            color: #999;
        }
        div.field > label {
            display: block;
        }
        div.field > input,
        div.field > textarea,
        div.field > select {
            width: 100%;
            padding: 6px 12px;
            box-sizing: border-box;
            border-radius: 4px;
            border: solid 1px #999;
        }
        .blog_box {
            width: 300px;
            line-height: 3px;
            margin-right: auto;
            margin-left: auto;
            border: 1px dotted #000;
            padding: 15px;
            margin-bottom: 20px;
        }
        

        @media screen and (max-width: 600px){
            .h1_title{
                margin-right: auto;
                margin-left: auto;
            }
            .profile_dd{
                text-align: left;
                margin: 0;

            }
            .box_1 {
                width: 33%;
            }
            .box_2 {
                width: 33%;
            }
            .box_3 {
                width: 33%;
            }
            .links_dd{
                overflow-wrap: break-word;
            }
            .works_table {
                width: 100%;
            }
            .works_td {
                font-size: 95%;
            }
            .main_form {
            width: 100%;
            margin-right: auto;
            margin-left: auto;
        }
            .thanks_p {
            margin-left: 10px;
        }
        }
        
        
    </style>
</head>
<body>

<header>
<h1>chibiharu's Room</h1>
<nav>
    <ul>
        <li>
            <a href="{% url 'myprofile:top' %}">TO</a>
            <a href="{% url 'myprofile:works' %}">Works</a>
            <a href="{% url 'myprofile:portfolio' %}">Portfolio</a>
            <a href="{% url 'blog:post_list' %}">Blog</a>
            <a href="{% url 'myprofile:form' %}">Contact</a>
        </li>
    </ul>
</nav>

</header>

{% block content %}{% endblock %}

</body>
</html>

myprofile/templates/myprofile/form.html
{% extends 'myprofile/base.html' %}

{% block title %}Harumasa's Room{% endblock %}

{% block content %}
    <h1 class="h1_title">Contact Form</h1>
    <form class="main_form" action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
                <span class="helptext">{{ field.help_text }}</span>
            {% endif %}
            {{ field.erros }}
        </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
{% endblock %}

myprofile/templates/myprofile/portfolio.html
{% extends 'myprofile/base.html' %}

{% block title %}Harumasa's Room - Portfolio{% endblock %}

{% block content%}
    <h1 class="h1_title">Portfolio</h1>
    


    

{% endblock%}

myprofile/templates/myprofile/thanks.html
{% extends 'myprofile/base.html' %}

{% block content %}
    <h1 class="h1_title">Thanks!</h1>
    <p class="thanks_p">Thank you for your inquiry<br>I will contact you shorttly<br>so please wait</p>
    
{% endblock %}

myprofile/templates/myprofile/top.html
{% extends 'myprofile/base.html' %}

{% block title %}chibiharu's Room{% endblock %}

{% block content %}
<h1 class="h1_title">ABOUT ME</h1>

<article class="top_article">
<div class="box_1">
<h2>Profile</h2>
<dl>
    <dt>Name</dt>
    <dd class="profile_dd">Harumasa Goto</dd>
    <dt>Age</dt>
    <dd class="profile_dd">24</dd>
    <dt>Location</dt>
    <dd class="profile_dd">Tokyo, Japan</dd>
    <dt>Affiliation</dt>
    <dd class="profile_dd">Secret</dd>
</dl>
</div>
<div class="box_2">
<h2>My Skills</h2>
<ul class="skill_ul">
    <li>Python</li>
    <li>Linux</li>
    <li>SQL</li>
    <li>HTML/CSS</li>
    <li>JavaScript</li>
    <li>VBA</li>
</ul>
</div>
<div class="box_3">
<h2>Links</h2>
<dl>
    <dt>MailAddress</dt>
    <dd class="links_dd">chibiharujijimasa@gmail.com</dd>
    <dt>Twitter</dt>
    <dd class="links_dd">chibiharu15</dd>
    <dt>Secret</dt>
    <dd class="links_dd">sample</dd>
</dl>
</div>
</article>
{% endblock %}

myprofile/templates/myprofile/works.html
{% extends 'myprofile/base.html' %}

{% block title %}chibiharu's Room - Works{% endblock %}

{% block content%}
    <h1 class="h1_title">Works</h1>

    <h2>Job career</h2>
    <table class="works_table">
        <tr>
            <th class="works_th">2020</th>
            <td class="works_td">埼玉県業訓練校にてITエンジニアとしての基礎を学ぶ</td>
        </tr>
        <tr>
            <th class="works_th">2020</th>
            <td class="works_td">某有名IT人材派遣会社にてインフラエンジニアとしてデビュー</td>
        </tr>
    </table>
    
    <h2>Job works</h2>

    <table class="works_table">
        <tr>
            <th class="works_th">Web Design</th>
            <td class="works_td">某社内Webサイトをゼロベースからリニューアル</td>
        </tr>
        <tr>
            <th class="works_th">Programming</th>
            <td class="works_td">VBAを用いた教育学習ツールの作成</td>
        </tr>
    </table>
{% endblock%}

reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>口コミサイト</title>
    <style>
        * {
            margin: 0;
        }
        body {
            color:#333;
        }
        body > header {
            font-size: 40px;
            background-color: #000;
            color: #fff;
            padding: 10px 30px;
        }

        main {
            margin-top: 20px;
            padding: 0 30px;
        }
        main > h1 {
            margin-bottom: 20px;
        }
        main > article {
            padding: 0 30px;
            margin-bottom: 20px;
        }

        .errorlist {
            margin: 0;
            padding: 0;
            list-style-type: none;
            color: red;
        }

        form > p {
            margin-bottom: 20px;
        }

        p > span.helptext {
            font-size: 14px;
            color: #999;
        }
        p > label {
            display: block;
        }

    </style>
</head>
<body>
<header>口コミサイト</header>
<main>
    {% block content %}{% endblock %}
</main>
</body>
</html>

reviews/templates/reviews/review_confirm_delete.html
{% extends 'reviews/base.html' %}

{% block content %}
    <p>{{ review.store_name }}のレビューを削除します。よろしいですか？</p>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>

{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'reviews/base.html' %}

{% block content %}
    <article>
        <h1>{{ review.store_name }}</h1>
        <p>{{ review.get_stars_display }} - {{ review.title }}</p>
        {{ review.text | linebreaks }}
    </article>
    <a href="{% url 'reviews:review_update' review.pk %}">更新</a>
    <a href="{% url 'reviews:review_delete' review.pk %}">削除</a>
{% endblock %}

reviews/templates/reviews/review_form.html
{% extends 'reviews/base.html' %}

{% block content %}
    <form action="" method="POST">
        {{ form.as_p }}
        {% if form.instance.pk %}
        <p>{{ form.instance.created_at }}</p>
        {% endif %}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h1>口コミ一覧</h1>
    {% for review in review_list %}
        <article>
            <h2><a href="{% url 'reviews:review_detail' review.pk %}">{{ review.store_name }}</a></h2>
            <p>{{ review.get_stars_display }} - {{ review.title }}</p>
        </article>
    {% endfor %}
    <a href="{% url 'reviews:review_create' %}">口コミ作成ページへ</a>
{% endblock %}